name: default
initial: pick
states:
  pick:
    role: pick
    next: do
  do:
    role: do
    next: eval
  eval:
    role: eval
    next:
      - if: step.exit_code == 0
        then: done
      - then: pick
  done:
    type: final
